spring:
  application:
    name: zamro-pmi
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  h2:
    console:
      enabled: true
server:
  port: 8080
application:
  version: 1.0


